### ISSUE TITLE
Bug: contributor attributed twice for same file

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/pizza-cli#191]
You can see this in action in https://github.com/open-sauced/landing-page/pull/362/files. Look for @zeucapua and you'll notice it appears twice on multiple files, e.g.

`components/sections/navigation/Header.tsx @brandonroberts @zeucapua @zeucapua`

![CleanShot 2024-09-15 at 08 59 23](https://github.com/user-attachments/assets/3bcec278-9399-4918-ada0-f0e0b3fd1f18)

This doesn't break anything and it's still a valid CODEOWNERS file, but it should be cleaned up.

**Comment by jpmcb** [comment]
Which version was this on? I think this was fixed recently so my guess is this was from an older version of the CLI

**Comment by nickytonline** [comment]
> Which version was this on? I think this was fixed recently so my guess is this was from an older version of the CLI

Looks like it was v1.5.0-beta.2.0.20240913205418-ea2b4a9594e9

**Comment by nickytonline** [comment]
Confirmed that with 2.1.0, this is still an issue.

Get latest from the open-sauced/landing-page project and run `pizza generate codeowners ./`. Notice Zeu appears twice.

![CleanShot 2024-09-16 at 14 26 59](https://github.com/user-attachments/assets/f2e3f313-a4b8-4c7c-a634-fe0e64955d33)

**Comment by jpmcb** [comment]
> Confirmed that with 2.1.0, this is still an issue.

Huh weird - I'll look into this. It shouldn't be able to have double the attributions since it uses a straight mapping of usernames to emails.

**Comment by takanome-dev** [comment]
Noticed the same:

```sh
pizza version
Version: v2.1.0
Sha: a659d86cd3a88d1856f4f1bd345e2b4d92fa4dd5
Built at: 2024-09-16-22:55:27
```

```md

.eslintrc.js @takanome-dev @takanome-dev
.github/workflows/development.yml @renovate[bot]
.prettierrc @takanome-dev @takanome-dev
CHANGELOG.md @El Hadji Malick Seck @El Hadji Malick Seck @dependabot[bot]
env.mjs @takanome-dev @takanome-dev
log.log @takanome-dev @takanome-dev
next.config.mjs @El Hadji Malick Seck @El Hadji Malick Seck
package.json @El Hadji Malick Seck @El Hadji Malick Seck @renovate[bot] @takanome-dev @takanome-dev
```

**Comment by jpmcb** [comment]
As a side note: this won't affect GitHub's `CODEOWNERS` automation. It'll still be able to automatically request review from whomever is attributed on that file

**Comment by nickytonline** [comment]
You can see this in action in this latest PR https://github.com/open-sauced/landing-page/pull/383. It's using v.2.2.0 of the pizza CLI, https://github.com/open-sauced/landing-page/actions/runs/11197287184/job/31127055020
